# Generated by Django 2.2.1 on 2019-07-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_trace_dir', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
                ('slug', models.CharField(editable=False, max_length=24, unique=True)),
                ('color', models.CharField(max_length=24, unique=True)),
                ('icon', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='TraceFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_file', models.CharField(max_length=200)),
                ('file_name', models.CharField(editable=False, max_length=100)),
                ('md5sum', models.CharField(max_length=32, unique=True)),
                ('center_lat', models.FloatField(max_length=20)),
                ('center_lon', models.FloatField(max_length=20)),
                ('zoom_level', models.IntegerField(blank=True, null=True)),
                ('geojson', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('duration', models.FloatField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizer.Sport')),
                ('trace_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wizer.TraceFiles')),
            ],
        ),
    ]
