# Generated by Django 2.2.1 on 2019-05-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity',
            field=models.CharField(default='none', max_length=400),
            preserve_default=False,
        ),
    ]
