# Generated by Django 2.2.1 on 2019-07-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0002_settings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='gpx_checker_interval',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
