# Generated by Django 2.2.5 on 2020-02-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0002_auto_20200208_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='max_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='min_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
