# Generated by Django 2.2.1 on 2019-05-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0003_auto_20190526_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sport',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
