# Generated by Django 2.2.1 on 2019-05-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0004_auto_20190526_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sport',
            name='color',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
