# Generated by Django 2.2.1 on 2019-07-24 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0004_auto_20190724_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.date(2019, 7, 24)),
        ),
    ]
