# Generated by Django 2.2.1 on 2019-07-24 16:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0005_auto_20190724_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 24, 16, 37, 17, 789326, tzinfo=utc)),
        ),
    ]
