# Generated by Django 2.2.5 on 2020-03-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0005_auto_20200308_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='aerobic_training_effect',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='anaerobic_training_effect',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='avg_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='avg_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='avg_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='avg_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='cadence_list',
            field=models.CharField(blank=True, max_length=10000000000, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='max_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='max_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='max_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='max_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='speed_list',
            field=models.CharField(blank=True, max_length=10000000000, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='temperature_list',
            field=models.CharField(blank=True, max_length=10000000000, null=True),
        ),
    ]
