# Generated by Django 2.2.5 on 2020-03-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0006_auto_20200308_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='min_cadence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='min_heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='min_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traces',
            name='min_temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
