# Generated by Django 2.2.1 on 2019-05-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0006_auto_20190526_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='sports_name_slug',
            field=models.CharField(default='NULL', editable=False, max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sport',
            name='sports_name',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
