# Generated by Django 2.2.1 on 2019-05-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0007_auto_20190526_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sports_name_slug',
            field=models.CharField(editable=False, max_length=24),
        ),
    ]
