# Generated by Django 2.2.1 on 2019-07-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0007_auto_20190724_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizer.Sport'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='trace_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizer.TraceFiles'),
        ),
    ]
