# Generated by Django 2.2.5 on 2020-03-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0008_auto_20200308_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traces',
            name='cadence_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='traces',
            name='coordinates',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='traces',
            name='speed_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
        migrations.AlterField(
            model_name='traces',
            name='temperature_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
    ]
