# Generated by Django 2.2.1 on 2019-08-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0008_auto_20190726_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_days', models.CharField(choices=[(365, 365), (180, 180), (30, 30), (10, 10), (5, 5)], default=30, max_length=12)),
                ('int_number_of_days', models.IntegerField(choices=[(365, 365), (180, 180), (30, 30), (10, 10), (5, 5)], default=30)),
            ],
        ),
    ]
