# Generated by Django 2.2.1 on 2019-06-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0009_auto_20190526_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='track_file',
            field=models.CharField(default='NULL', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
