# Generated by Django 2.2.1 on 2019-08-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0009_dashboardsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardsettings',
            name='number_of_days',
        ),
    ]
