# Generated by Django 2.2.5 on 2020-03-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0009_auto_20200308_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traces',
            name='elevation',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
    ]
