# Generated by Django 2.2.1 on 2019-08-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0010_remove_dashboardsettings_number_of_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardsettings',
            old_name='int_number_of_days',
            new_name='number_of_days',
        ),
    ]
