# Generated by Django 2.2.1 on 2019-06-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0010_auto_20190601_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sport',
            old_name='sports_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='sports_name_slug',
            new_name='name_slug',
        ),
    ]
