# Generated by Django 2.2.5 on 2020-03-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0010_auto_20200308_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traces',
            old_name='coordinates',
            new_name='coordinates_list',
        ),
        migrations.RenameField(
            model_name='traces',
            old_name='elevation',
            new_name='elevation_list',
        ),
        migrations.AlterField(
            model_name='traces',
            name='avg_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traces',
            name='max_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traces',
            name='min_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
