# Generated by Django 2.2.1 on 2019-08-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0011_auto_20190818_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashboardSettings',
        ),
        migrations.AddField(
            model_name='settings',
            name='number_of_days',
            field=models.IntegerField(choices=[(365, 365), (180, 180), (30, 30), (10, 10), (5, 5)], default=30),
        ),
    ]
