# Generated by Django 2.2.5 on 2020-03-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0012_auto_20200314_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='reimporter_updates_all',
            field=models.BooleanField(default=False, verbose_name='Force Update all Fields: '),
        ),
    ]
