# Generated by Django 2.2.1 on 2019-08-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0012_auto_20190818_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='trace_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wizer.TraceFiles'),
        ),
    ]
