# Generated by Django 2.2.1 on 2019-06-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0012_auto_20190601_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='track_file',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
