# Generated by Django 2.2.1 on 2019-08-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0013_auto_20190828_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
