# Generated by Django 2.2.1 on 2019-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0013_auto_20190601_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=models.CharField(editable=False, max_length=24),
        ),
    ]
