# Generated by Django 2.2.5 on 2020-03-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0014_remove_activity_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
