# Generated by Django 2.2.1 on 2019-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0014_auto_20190602_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='color',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='icon',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=models.CharField(editable=False, max_length=24, unique=True),
        ),
    ]
