# Generated by Django 2.2.1 on 2019-09-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0014_auto_20190828_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_file', models.CharField(max_length=200)),
                ('file_name', models.CharField(editable=False, max_length=100)),
                ('md5sum', models.CharField(max_length=32, unique=True)),
                ('center_lat', models.FloatField(max_length=20)),
                ('center_lon', models.FloatField(max_length=20)),
                ('zoom_level', models.IntegerField(blank=True, null=True)),
                ('geometry', models.CharField(max_length=100000000)),
            ],
        ),
    ]
