# Generated by Django 2.2.1 on 2019-06-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0015_auto_20190602_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='track_file',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
