# Generated by Django 2.2.1 on 2019-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0016_auto_20190602_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
