# Generated by Django 3.0.3 on 2020-04-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0016_traces_timestamps_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='delete_files_after_import',
            field=models.BooleanField(default=False, verbose_name='Delete fit Files after Copying: '),
        ),
    ]
