# Generated by Django 3.0.3 on 2020-04-29 18:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0018_auto_20200414_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='color_field',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
