# Generated by Django 2.2.1 on 2019-06-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0018_auto_20190602_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='track_file',
            new_name='trace_file',
        ),
    ]
