# Generated by Django 2.2.1 on 2019-09-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0020_auto_20190914_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traces',
            old_name='geometry',
            new_name='coordinates',
        ),
    ]
