# Generated by Django 2.2.1 on 2019-06-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0020_auto_20190602_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='trace_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
