# Generated by Django 2.2.1 on 2019-06-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0021_auto_20190602_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_trace_dir', models.FilePathField(max_length=120)),
            ],
        ),
    ]
