# Generated by Django 2.2.1 on 2019-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0021_auto_20190914_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='trace_opacity',
            field=models.FloatField(default=0.7, max_length=20),
        ),
        migrations.AddField(
            model_name='settings',
            name='trace_width',
            field=models.FloatField(default=3.0, max_length=20),
        ),
    ]
