# Generated by Django 2.2.1 on 2019-06-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0022_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='path_to_trace_dir',
            field=models.CharField(max_length=120),
        ),
    ]
