# Generated by Django 2.2.1 on 2019-09-16 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0023_auto_20190916_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='Distance:'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(verbose_name='Duration:'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizer.Sport', verbose_name='Sport:'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Activity Name:'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='color',
            field=models.CharField(max_length=24, unique=True, verbose_name='Color:'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='icon',
            field=models.CharField(max_length=24, verbose_name='Icon:'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=24, unique=True, verbose_name='Sport Name:'),
        ),
    ]
