# Generated by Django 2.2.1 on 2019-09-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0024_auto_20190916_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='trace_opacity',
            field=models.FloatField(default=0.7, max_length=20, verbose_name='Opacity of Traces:'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='trace_width',
            field=models.FloatField(default=3.0, max_length=20, verbose_name='Width of Traces:'),
        ),
    ]
