# Generated by Django 2.2.1 on 2019-09-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0026_auto_20190918_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='altitude',
            field=models.CharField(blank=True, max_length=10000000000, null=True),
        ),
        migrations.AlterField(
            model_name='traces',
            name='coordinates',
            field=models.CharField(max_length=10000000000),
        ),
    ]
