# Generated by Django 2.2.5 on 2019-09-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0028_auto_20190920_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='color',
            field=models.CharField(max_length=24, verbose_name='Color:'),
        ),
    ]
