# Generated by Django 2.2.5 on 2019-09-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0029_auto_20190920_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='plotting_style',
            field=models.CharField(choices=[('bar', 'stacked bar chart'), ('line', 'multiline')], default='line', max_length=120),
        ),
        migrations.AlterField(
            model_name='settings',
            name='number_of_days',
            field=models.IntegerField(choices=[(99999, 'all'), (365, 365), (180, 180), (90, 90), (30, 30), (10, 10), (5, 5)], default=30),
        ),
    ]
