# Generated by Django 2.2.5 on 2019-09-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0030_auto_20190920_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='plotting_style',
            field=models.CharField(choices=[('bar', 'stacked bar chart'), ('line', 'multiline')], default='line', max_length=120, verbose_name='Plotting Style:'),
        ),
    ]
