# Generated by Django 2.2.5 on 2019-09-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0031_auto_20190920_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='gpx_checker_interval',
            field=models.IntegerField(default=60, verbose_name='GPX File Checker Time Interval:'),
        ),
    ]
