# Generated by Django 2.2.5 on 2019-09-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0032_auto_20190923_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='user',
        ),
    ]
