# Generated by Django 2.2.5 on 2019-09-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0033_remove_settings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='gpx_checker_interval',
        ),
        migrations.AddField(
            model_name='settings',
            name='file_checker_interval',
            field=models.IntegerField(default=60, verbose_name='File Checker Time Interval:'),
        ),
    ]
