# Generated by Django 2.2.5 on 2019-09-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0034_auto_20190923_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='number_of_days',
            field=models.IntegerField(choices=[(9999, 'all'), (365, 365), (180, 180), (90, 90), (30, 30), (10, 10), (5, 5)], default=30),
        ),
    ]
