# Generated by Django 2.2.5 on 2019-09-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0035_auto_20190924_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='path_to_garmin_device',
            field=models.CharField(default='/path/to/your/garmin-device/', max_length=120, verbose_name='Path to Garmin Device:'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='path_to_trace_dir',
            field=models.CharField(default='/path/to/your/traces/', max_length=120, verbose_name='Path to Traces Directory:'),
        ),
    ]
