# Generated by Django 2.2.5 on 2019-09-24 20:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0036_auto_20190924_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 9, 24, 20, 10, 40, 45954, tzinfo=utc), verbose_name='Time:'),
            preserve_default=False,
        ),
    ]
