# Generated by Django 2.2.5 on 2019-09-25 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0038_auto_20190924_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='duration',
            new_name='duration_old',
        ),
        migrations.AlterField(
            model_name='activity',
            name='dur2',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='dur2:'),
        ),
    ]
