# Generated by Django 2.2.5 on 2019-09-25 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0039_auto_20190925_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='dur2',
        ),
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='Duration:'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_old',
            field=models.IntegerField(verbose_name='duration-old:'),
        ),
    ]
