# Generated by Django 2.2.5 on 2019-09-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0040_auto_20190925_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='title',
            new_name='name',
        ),
    ]
