# Generated by Django 2.2.5 on 2019-09-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0043_auto_20190925_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='map_type',
            field=models.CharField(choices=[('osm', 'Open Street Map'), ('opentopomap', 'Open Topo Map')], default='opentopomap', max_length=120, verbose_name='Map Type:'),
        ),
    ]
