# Generated by Django 2.2.5 on 2019-09-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0044_settings_map_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='related_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wizer.Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='trace_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wizer.Traces'),
        ),
    ]
