# Generated by Django 2.2.5 on 2019-09-26 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0045_auto_20190926_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traces',
            name='related_activity',
        ),
        migrations.AlterField(
            model_name='activity',
            name='trace_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wizer.Traces'),
        ),
    ]
