# Generated by Django 2.2.5 on 2019-12-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0046_auto_20190926_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Distance:'),
        ),
    ]
