# Generated by Django 2.2.5 on 2020-01-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0049_traces_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traces',
            name='calories',
        ),
        migrations.AddField(
            model_name='activity',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
