# Generated by Django 2.2.5 on 2020-01-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0050_auto_20200122_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='map_type',
        ),
    ]
