# Generated by Django 3.1.5 on 2021-01-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wizer", "0001_squashed_0014_auto_20210112_1924"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="suitable_for_best_sections",
            field=models.BooleanField(default=True, verbose_name="Determine Awards for this Activity:"),
        ),
        migrations.AlterField(
            model_name="bestsection",
            name="section_distance",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bestsectiontopscores",
            name="section",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wizer.bestsection"),
        ),
        migrations.AlterField(
            model_name="traces",
            name="avg_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="traces",
            name="max_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="traces",
            name="min_temperature",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
