# Generated by Django 2.2.5 on 2020-02-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0003_auto_20200214_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Description:'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default='unknown', max_length=200, verbose_name='Activity Name:'),
        ),
    ]
