# Generated by Django 3.1.5 on 2021-01-29 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wizer", "0003_auto_20210128_1816"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BestSectionTopScores",
        ),
    ]
