# Generated by Django 3.1.5 on 2021-01-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wizer", "0004_delete_bestsectiontopscores"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="suitable_for_best_sections",
            new_name="evaluates_for_awards",
        ),
        migrations.RenameField(
            model_name="sport",
            old_name="suitable_for_best_sections",
            new_name="evaluates_for_awards",
        ),
    ]
