# Generated by Django 3.0.8 on 2020-12-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizer", "0005_auto_20201010_1101"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="run_file_importer_in_background",
            field=models.BooleanField(default=False, verbose_name="Run File Importer in Background"),
        ),
    ]
