# Generated by Django 3.0.8 on 2020-12-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wizer", "0006_settings_run_file_importer_in_background"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="file_checker_interval",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="run_file_importer_in_background",
        ),
    ]
