# Generated by Django 2.2.5 on 2020-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0007_auto_20200308_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traces',
            name='heart_rate_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
    ]
