# Generated by Django 3.0.8 on 2020-12-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizer", "0008_bestsection_bestsectiontype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bestsection",
            name="secion_type",
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name="BestSectionType",
        ),
    ]
