# Generated by Django 3.0.8 on 2020-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizer", "0010_auto_20201230_1038"),
    ]

    operations = [
        migrations.AddField(
            model_name="bestsection",
            name="section_distance",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
