# Generated by Django 2.2.5 on 2020-03-14 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0011_auto_20200314_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traces',
            old_name='elevation_list',
            new_name='altitude_list',
        ),
    ]
