# Generated by Django 3.0.8 on 2020-12-30 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wizer", "0011_bestsection_section_distance"),
    ]

    operations = [
        migrations.CreateModel(
            name="BestSectionTopScores",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("section_type", models.CharField(max_length=120)),
                ("section_distance", models.IntegerField()),
                ("max_value", models.FloatField()),
                ("rank", models.IntegerField(choices=[(1, "First"), (2, "Second"), (3, "Third")])),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("activity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wizer.Activity")),
                ("sport", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wizer.Sport")),
            ],
        ),
    ]
