# Generated by Django 3.0.8 on 2021-01-01 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wizer", "0012_bestsectiontopscores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bestsectiontopscores",
            name="max_value",
        ),
        migrations.RemoveField(
            model_name="bestsectiontopscores",
            name="section_distance",
        ),
        migrations.RemoveField(
            model_name="bestsectiontopscores",
            name="section_type",
        ),
        migrations.AddField(
            model_name="bestsectiontopscores",
            name="section",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="wizer.BestSection"),
            preserve_default=False,
        ),
    ]
