# Generated by Django 2.2.5 on 2020-03-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0013_settings_reimporter_updates_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='calories',
        ),
    ]
