# Generated by Django 3.1.5 on 2021-01-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizer", "0013_auto_20210101_1818"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settings",
            name="reimporter_updates_all",
        ),
        migrations.AlterField(
            model_name="settings",
            name="path_to_trace_dir",
            field=models.CharField(
                default="/workspaces/workoutizer/tracks", max_length=120, verbose_name="Path to Traces Directory:"
            ),
        ),
    ]
