# Generated by Django 2.2.5 on 2020-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0015_traces_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='traces',
            name='timestamps_list',
            field=models.CharField(default='[]', max_length=10000000000),
        ),
    ]
