# Generated by Django 3.0.3 on 2020-04-30 04:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0019_sport_color_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='color_field',
        ),
        migrations.AlterField(
            model_name='sport',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Color:'),
        ),
    ]
