# Generated by Django 3.0.3 on 2020-04-30 04:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0020_auto_20200430_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='color',
            field=colorfield.fields.ColorField(default='#42FF71', max_length=18, verbose_name='Color:'),
        ),
    ]
