# Generated by Django 3.0.3 on 2020-05-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0022_activity_is_demo_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('elapsed_time', models.DurationField()),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_long', models.FloatField(blank=True, null=True)),
                ('end_lat', models.FloatField(blank=True, null=True)),
                ('end_long', models.FloatField(blank=True, null=True)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizer.Traces')),
            ],
        ),
    ]
