# Generated by Django 3.0.3 on 2020-05-24 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0023_lap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date:'),
        ),
    ]
