# Generated by Django 3.0.3 on 2020-05-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0024_auto_20200524_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='plotting_style',
        ),
    ]
