# Generated by Django 3.0.3 on 2020-05-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0025_remove_settings_plotting_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='was_trigger_manual',
            field=models.BooleanField(default=True),
        ),
    ]
