# Generated by Django 3.0.3 on 2020-06-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0026_lap_was_trigger_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='was_trigger_manual',
        ),
        migrations.AddField(
            model_name='lap',
            name='lap_trigger',
            field=models.CharField(default='not-specified', max_length=120),
            preserve_default=False,
        ),
    ]
