# Generated by Django 3.0.3 on 2020-06-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0027_auto_20200601_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lap',
            old_name='lap_trigger',
            new_name='trigger',
        ),
    ]
