# Generated by Django 3.0.3 on 2020-06-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0028_auto_20200610_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
