# Generated by Django 3.0.3 on 2020-06-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0032_auto_20200628_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lap',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description:'),
        ),
    ]
