# Generated by Django 3.0.3 on 2020-06-29 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0033_auto_20200629_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lap',
            name='description',
        ),
    ]
