# Generated by Django 3.0.3 on 2020-06-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0034_remove_lap_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lap',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Label:'),
        ),
    ]
