# Generated by Django 3.0.3 on 2020-06-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizer', '0035_lap_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='trace_opacity',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='trace_width',
        ),
    ]
