# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: black formatting
        run: |
          pip install black
          black --check -l 121 .
      - name: isort formatting
        if: ${{ always() }}
        run: |
          pip install isort
          isort -c .
      - name: flake8 formatting
        if: ${{ always() }}
        run: |
          pip install flake8
          flake8 .
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -r setup/requirements/dev-requirements.txt
      - name: Run Unit Tests
        run: |
          pytest wizer/tests/unit_tests -v
      - name: Run Integration Tests
        run: |
          pytest wizer/tests/integration_tests -v
#      - name: Run end2end Test
#        run: |
#          pytest wizer/tests/end2end -v
