
name: Release

on:
  release:
    types: [created]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install -r setup/requirements/dev-requirements.txt
        pip install -r setup/requirements/requirements.txt
        pip install -e . --no-deps
    - name: Run Tests
      run: |
        pytest wkz/tests -v -n2

  build:
    name: Build, Check & Release
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install setuptools wheel
    - name: Build workoutizer
      run: |
        python setup.py sdist bdist_wheel
    - name: Install workoutizer
      run: |
        pip install dist/workoutizer-*.whl
    - name: Check Installation
      env:
        WKZ_LOG_LEVEL: DEBUG
      run: |
        wkz init --demo
        wkz check
    - name: Install Publishing Dependencies
      run: |
        pip install twine
    - name: Release
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
