
name: Run Tests and Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r setup/requirements/dev-requirements.txt
          pip install -e .
      - name: Run all Tests
        run: |
          pytest wizer/tests/ -v
      - name: Init
        env:
          WKZ_LOG_LEVEL: DEBUG
        run: |
          wkz init
      - name: Check
        run: |
          wkz check
