
name: Test

on: push

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: black formatting
      run: |
        python -m pip install --upgrade pip
        pip install black
        black --check .
    - name: flake8 formatting
      if: always()
      run: |
        pip install flake8
        flake8 .

  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      if: always()
      run: |
        pip install -r setup/requirements/dev-requirements.txt
        pip install -e .

    - name: Run Unit Tests
      if: always()
      run: |
        pytest wkz/tests/unit_tests -vv -n2

    - name: Run DB Tests
      if: always()
      run: |
        pytest wkz/tests/db_tests -vv -n2

    - name: Run Browser Tests
      if: always()
      run: |
        pytest wkz/tests/browser_tests -vv -n2

    - name: Init
      if: always()
      env:
        WKZ_LOG_LEVEL: DEBUG
      run: |
        wkz init --demo

    - name: Check
      if: always()
      run: |
        wkz check
