
name: Upload Python Package

on: push
  # release:
  #   types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r setup/requirements/requirements.txt
    - name: Build workoutizer
      run: |
        python setup.py sdist bdist_wheel
    - name: Install workoutizer
      run: |
        pip install dist/workoutizer-*.whl --no-deps
    - name: Check Installation
      env:
        WKZ_LOG_LEVEL: DEBUG
      run: |
        wkz init
        wkz check

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build workoutizer
      run: |
        python setup.py sdist bdist_wheel
    - name: Release
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        ls -l dist/
        # twine upload dist/*
