
name: Run Python Tests

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: black formatting
        run: |
          pip install black
          black --check .
      - name: flake8 formatting
        if: ${{ always() }}
        run: |
          pip install flake8
          flake8 .
      - name: Install dependencies
        if: ${{ always() }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -r setup/requirements/dev-requirements.txt
      - name: Run Unit Tests
        if: ${{ always() }}
        run: |
          pytest wizer/tests/unit_tests -v
      - name: Run Integration Tests
        if: ${{ always() }}
        run: |
          pytest wizer/tests/integration_tests -v
      - name: Run Endpoint Tests
        if: ${{ always() }}
        run: |
          pytest wizer/tests/endpoint_tests -v
      - name: Run Browser Tests
        if: ${{ always() }}
        run: |
          pytest wizer/tests/browser_tests -v
