
name: Upload Python Package

on: push
  # release:
  #   types: [created]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install -r setup/requirements/dev-requirements.txt
        pip install -r setup/requirements/requirements.txt
        pip install -e . --no-deps
    - name: Run Tests
      run: |
        pytest wizer/tests -v

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install setuptools wheel twine
    - name: Build workoutizer
      run: |
        python setup.py sdist bdist_wheel
    - name: Install workoutizer
      run: |
        pip install dist/workoutizer-*.whl --no-deps
    - name: Check Installation
      env:
        WKZ_LOG_LEVEL: DEBUG
      run: |
        wkz init
        wkz check

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install setuptools wheel twine
    - name: Release
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        ls -l dist/
        # twine upload dist/*
