
name: Release

on:
  release:
    types: [created]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install --upgrade poetry
        poetry install
    - name: Run Tests
      run: |
        pytest tests/ -vv -n2 --color=yes

  build:
    name: Build, Check & Release
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install --upgrade poetry
    - name: Build workoutizer
      run: |
        poetry build
    - name: Install workoutizer
      run: |
        poetry install
    - name: Check Installation
      env:
        WKZ_LOG_LEVEL: DEBUG
      run: |
        wkz init --demo
        wkz check
    - name: Release
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish
