
name: Release

on: push
  # release:
  #   types: [created]

jobs:
  build:
    name: Build, Check & Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install --upgrade poetry
    - name: Build workoutizer
      run: |
        poetry build
    - name: Install workoutizer
      run: |
        poetry install --no-interaction
    - name: Check Installation
      env:
        WKZ_LOG_LEVEL: DEBUG
      run: |
        wkz init --demo
        wkz check
    - name: Release
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish --dry-run
