
name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install --upgrade poetry
    - name: Build workoutizer
      run: |
        poetry build
    - name: Release
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
